<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <OutputType Condition="$(RuntimeIdentifier.StartsWith('win'))">WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>APOD.UI</RootNamespace>
    <Version>2.2.0</Version>
    <Description>Versión gráfica (Avalonia) de APOD Wallpapers.</Description>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <PackageIcon>favicon.ico</PackageIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained Condition="'$(RuntimeIdentifier)' != ''">true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\APOD.Core\APOD.Core.csproj" />
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Controls.WebView" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.20" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
  </ItemGroup>

  <ItemGroup>
    <None Include="favicon.ico">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <Target Name="EnsureSingleFile" AfterTargets="Publish" Condition="'$(SelfContained)' == 'true'">
    <ItemGroup>
      <ExtraFiles Include="$(PublishDir)**/*.pdb;$(PublishDir)**/*.deps.json;$(PublishDir)**/*.runtimeconfig.json" />
    </ItemGroup>
    <Delete Files="@(ExtraFiles)" />
  </Target>

</Project>
